# Generated by Django 5.1.3 on 2024-12-03 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estacionamento', '0003_estacionamento'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cliente',
            old_name='cpf',
            new_name='CPF',
        ),
        migrations.RenameField(
            model_name='veiculo',
            old_name='clinete',
            new_name='cliente',
        ),
        migrations.AlterField(
            model_name='veiculo',
            name='placa',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
