# Generated by Django 5.1.3 on 2024-12-03 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estacionamento', '0004_rename_cpf_cliente_cpf_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='estacionamento',
            old_name='clienete',
            new_name='cliente',
        ),
    ]
