# Generated by Django 5.1.3 on 2024-12-05 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estacionamento', '0005_rename_clienete_estacionamento_cliente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estacionamento',
            name='horario_entrada',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='estacionamento',
            name='horario_saida',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
