# Generated by Django 5.1.3 on 2024-12-05 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estacionamento', '0006_alter_estacionamento_horario_entrada_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estacionamento',
            name='valor_pagamento',
        ),
    ]
